# Generated by Django 3.0 on 2019-12-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('control_type', models.CharField(choices=[('Primitive', 'Primitive'), ('Corpse', 'Corpse'), ('Gaussian', 'Gaussian'), ('CinBB', 'CinBB')], max_length=200)),
                ('maximum_rabi_rate', models.FloatField()),
                ('polar_angle', models.FloatField()),
            ],
        ),
    ]
