# Generated by Django 3.0 on 2019-12-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='control_type',
        ),
        migrations.AddField(
            model_name='control',
            name='type',
            field=models.CharField(choices=[('Primitive', 'Primitive'), ('Corpse', 'CORPSE'), ('Gaussian', 'Gaussian'), ('CinBB', 'CinBB')], default='Primitive', max_length=200),
        ),
    ]
