# Generated by Django 3.0 on 2019-12-17 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_api', '0002_auto_20191216_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='maximum_rabi_rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='control',
            name='polar_angle',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
